// <auto-generated />
using System;
using BoneVisQA.Repositories.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoneVisQA.Repositories.Migrations
{
    [DbContext(typeof(BoneVisQADbContext))]
    [Migration("AddClassIdToCaseViewLogs")]
    partial class AddClassIdToCaseViewLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseViewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("view_count");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "CaseId")
                        .HasDatabaseName("idx_case_view_logs_student_case");

                    b.ToTable("case_view_logs");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.AcademicClass", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.User", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoneVisQA.Repositories.Models.BoneSpecialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("ClassSpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Expert");
                    b.Navigation("Lecturer");
                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseViewLog", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.MedicalCase", "Case")
                        .WithMany("CaseViewLogs")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoneVisQA.Repositories.Models.AcademicClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Student")
                        .WithMany("CaseViewLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                    b.Navigation("Class");
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
