// <auto-generated />
using System;
using BoneVisQA.Repositories.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace BoneVisQA.Repositories.Migrations
{
    [DbContext(typeof(BoneVisQADbContext))]
    partial class BoneVisQADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "graphql", "pg_graphql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoneVisQA.Repositories.Models.AcademicClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("semester");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("academic_classes_pkey");

                    b.HasIndex("LecturerId");

                    b.ToTable("academic_classes");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("announcements_pkey");

                    b.HasIndex(new[] { "ClassId" }, "idx_announcements_class");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Coordinates")
                        .HasColumnType("jsonb")
                        .HasColumnName("coordinates");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("case_annotations_pkey");

                    b.HasIndex(new[] { "ImageId" }, "idx_case_annotations_image");

                    b.ToTable("case_annotations");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<string>("DifferentialDiagnoses")
                        .HasColumnType("text")
                        .HasColumnName("differential_diagnoses");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::text");

                    b.Property<string>("StructuredDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("structured_diagnosis");

                    b.HasKey("Id")
                        .HasName("case_answers_pkey");

                    b.HasIndex("ReviewedById");

                    b.HasIndex(new[] { "QuestionId" }, "idx_case_answers_question");

                    b.ToTable("case_answers");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseTag", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CaseId", "TagId")
                        .HasName("case_tags_pkey");

                    b.HasIndex(new[] { "CaseId" }, "idx_case_tags_case");

                    b.HasIndex(new[] { "TagId" }, "idx_case_tags_tag");

                    b.ToTable("case_tags");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseViewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("case_view_logs_pkey");

                    b.HasIndex("CaseId");

                    b.HasIndex(new[] { "StudentId", "CaseId" }, "idx_case_view_logs_student_case");

                    b.ToTable("case_view_logs");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "Name" }, "categories_name_key")
                        .IsUnique();

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Citation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_id");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity_score");

                    b.HasKey("Id")
                        .HasName("citations_pkey");

                    b.HasIndex("ChunkId");

                    b.HasIndex(new[] { "AnswerId", "ChunkId" }, "citations_answer_id_chunk_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "AnswerId" }, "idx_citations_answer");

                    b.ToTable("citations");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ClassEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<string>("ClassName")
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("class_enrollments_pkey");

                    b.HasIndex(new[] { "ClassId", "StudentId" }, "class_enrollments_class_id_student_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "idx_class_enrollments_student");

                    b.ToTable("class_enrollments");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ClassQuiz", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ClassId", "QuizId");

                    b.HasIndex("QuizId");

                    b.ToTable("class_quizzes");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ClassTag", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ClassId", "TagId")
                        .HasName("class_tags_pkey");

                    b.HasIndex(new[] { "ClassId" }, "idx_class_tags_class");

                    b.HasIndex(new[] { "TagId" }, "idx_class_tags_tag");

                    b.ToTable("class_tags");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("IndexingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indexing_status");

                    b.Property<bool>("IsOutdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_outdated");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_order");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid")
                        .HasColumnName("doc_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flagged");

                    b.HasKey("Id")
                        .HasName("document_chunks_pkey");

                    b.HasIndex(new[] { "DocId", "ChunkOrder" }, "document_chunks_doc_id_chunk_order_key")
                        .IsUnique();

                    b.ToTable("document_chunks");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.DocumentTag", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex(new[] { "DocumentId" }, "idx_document_tags_document");

                    b.HasIndex(new[] { "TagId" }, "idx_document_tags_tag");

                    b.ToTable("document_tags");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ExpertReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_id");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.HasKey("Id")
                        .HasName("expert_reviews_pkey");

                    b.HasIndex("AnswerId");

                    b.HasIndex(new[] { "ExpertId", "AnswerId" }, "expert_reviews_expert_id_answer_id_key")
                        .IsUnique();

                    b.ToTable("expert_reviews");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.LearningStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<double?>("AvgQuizScore")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_quiz_score");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<string>("ErrorDistribution")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_distribution");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int?>("TotalCasesViewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_cases_viewed");

                    b.Property<int?>("TotalQuestionsAsked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_questions_asked");

                    b.HasKey("Id")
                        .HasName("learning_statistics_pkey");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "StudentId", "ClassId" }, "learning_statistics_student_id_class_id_key")
                        .IsUnique();

                    b.ToTable("learning_statistics");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.MedicalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approved");

                    b.Property<string>("KeyFindings")
                        .HasColumnType("text")
                        .HasColumnName("key_findings");

                    b.Property<string>("ReflectiveQuestions")
                        .HasColumnType("text")
                        .HasColumnName("reflective_questions");

                    b.Property<string>("SuggestedDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("suggested_diagnosis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("medical_cases_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("medical_cases");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.MedicalImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Modality")
                        .HasColumnType("text")
                        .HasColumnName("modality");

                    b.HasKey("Id")
                        .HasName("medical_images_pkey");

                    b.HasIndex(new[] { "CaseId" }, "idx_medical_images_case");

                    b.ToTable("medical_images");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("password_reset_tokens_pkey");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_password_reset_tokens_token");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_time");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_time");

                    b.Property<int?>("PassingScore")
                        .HasColumnType("integer")
                        .HasColumnName("passing_score");

                    b.Property<int?>("TimeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("quizzes_pkey");

                    b.ToTable("quizzes");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("quiz_attempts_pkey");

                    b.HasIndex("QuizId");

                    b.HasIndex(new[] { "StudentId", "QuizId" }, "idx_quiz_attempts_student_quiz");

                    b.HasIndex(new[] { "StudentId", "QuizId" }, "quiz_attempts_student_id_quiz_id_key")
                        .IsUnique();

                    b.ToTable("quiz_attempts");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<string>("OptionA")
                        .HasColumnType("text")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .HasColumnType("text")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .HasColumnType("text")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .HasColumnType("text")
                        .HasColumnName("option_d");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("quiz_questions_pkey");

                    b.HasIndex("CaseId");

                    b.HasIndex("QuizId");

                    b.ToTable("quiz_questions");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.StudentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AnnotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("annotation_id");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomCoordinates")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_coordinates");

                    b.Property<string>("CustomImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("custom_image_url");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("student_questions_pkey");

                    b.HasIndex("AnnotationId");

                    b.HasIndex(new[] { "CaseId" }, "idx_student_questions_case");

                    b.HasIndex(new[] { "StudentId" }, "idx_student_questions_student");

                    b.ToTable("student_questions");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.StudentQuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("StudentAnswer")
                        .HasColumnType("text")
                        .HasColumnName("student_answer");

                    b.HasKey("Id")
                        .HasName("student_quiz_answers_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "AttemptId", "QuestionId" }, "student_quiz_answers_attempt_id_question_id_key")
                        .IsUnique();

                    b.ToTable("student_quiz_answers");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.HasIndex(new[] { "Type" }, "idx_tags_type");

                    b.HasIndex(new[] { "Name", "Type" }, "tags_name_type_key")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("SchoolCohort")
                        .HasColumnType("text")
                        .HasColumnName("school_cohort");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_users_is_active");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "RoleId" }, "idx_user_roles_role");

                    b.HasIndex(new[] { "UserId" }, "idx_user_roles_user");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "user_roles_user_id_role_id_key")
                        .IsUnique();

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.AcademicClass", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.User", "Lecturer")
                        .WithMany("AcademicClasses")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("academic_classes_lecturer_id_fkey");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Announcement", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.AcademicClass", "Class")
                        .WithMany("Announcements")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("announcements_class_id_fkey");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseAnnotation", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.MedicalImage", "Image")
                        .WithMany("CaseAnnotations")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("case_annotations_image_id_fkey");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseAnswer", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.StudentQuestion", "Question")
                        .WithMany("CaseAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("case_answers_question_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "ReviewedBy")
                        .WithMany("CaseAnswers")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("case_answers_reviewed_by_id_fkey");

                    b.Navigation("Question");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseTag", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.MedicalCase", "Case")
                        .WithMany("CaseTags")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("case_tags_case_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.Tag", "Tag")
                        .WithMany("CaseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("case_tags_tag_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseViewLog", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.MedicalCase", "Case")
                        .WithMany("CaseViewLogs")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("case_view_logs_case_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Student")
                        .WithMany("CaseViewLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("case_view_logs_student_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Citation", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.CaseAnswer", "Answer")
                        .WithMany("Citations")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citations_answer_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.DocumentChunk", "Chunk")
                        .WithMany("Citations")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citations_chunk_id_fkey");

                    b.Navigation("Answer");

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ClassEnrollment", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.AcademicClass", "Class")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_enrollments_class_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Student")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_enrollments_student_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ClassQuiz", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.AcademicClass", "Class")
                        .WithMany("ClassQuizzes")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoneVisQA.Repositories.Models.Quiz", "Quiz")
                        .WithMany("ClassQuizzes")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ClassTag", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.AcademicClass", "Class")
                        .WithMany("ClassTags")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_tags_class_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.Tag", "Tag")
                        .WithMany("ClassTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("class_tags_tag_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Document", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.Category", "Category")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("documents_category_id_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.DocumentChunk", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.Document", "Doc")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("document_chunks_doc_id_fkey");

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.DocumentTag", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.Document", "Document")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoneVisQA.Repositories.Models.Tag", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.ExpertReview", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.CaseAnswer", "Answer")
                        .WithMany("ExpertReviews")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("expert_reviews_answer_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Expert")
                        .WithMany("ExpertReviews")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("expert_reviews_expert_id_fkey");

                    b.Navigation("Answer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.LearningStatistic", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.AcademicClass", "Class")
                        .WithMany("LearningStatistics")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("learning_statistics_class_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Student")
                        .WithMany("LearningStatistics")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("learning_statistics_student_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.MedicalCase", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.Category", "Category")
                        .WithMany("MedicalCases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("medical_cases_category_id_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.MedicalImage", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.MedicalCase", "Case")
                        .WithMany("MedicalImages")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("medical_images_case_id_fkey");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.PasswordResetToken", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("password_reset_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.QuizAttempt", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_attempts_quiz_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Student")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_attempts_student_id_fkey");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.QuizQuestion", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.MedicalCase", "Case")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("quiz_questions_case_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_questions_quiz_id_fkey");

                    b.Navigation("Case");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.StudentQuestion", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.CaseAnnotation", "Annotation")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("student_questions_annotation_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.MedicalCase", "Case")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("CaseId")
                        .HasConstraintName("student_questions_case_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "Student")
                        .WithMany("StudentQuestions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_questions_student_id_fkey");

                    b.Navigation("Annotation");

                    b.Navigation("Case");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.StudentQuizAnswer", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.QuizAttempt", "Attempt")
                        .WithMany("StudentQuizAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_quiz_answers_attempt_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.QuizQuestion", "Question")
                        .WithMany("StudentQuizAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("student_quiz_answers_question_id_fkey");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.UserRole", b =>
                {
                    b.HasOne("BoneVisQA.Repositories.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("BoneVisQA.Repositories.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.AcademicClass", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("ClassQuizzes");

                    b.Navigation("ClassTags");

                    b.Navigation("LearningStatistics");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseAnnotation", b =>
                {
                    b.Navigation("StudentQuestions");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.CaseAnswer", b =>
                {
                    b.Navigation("Citations");

                    b.Navigation("ExpertReviews");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Category", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("MedicalCases");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Document", b =>
                {
                    b.Navigation("DocumentChunks");

                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.DocumentChunk", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.MedicalCase", b =>
                {
                    b.Navigation("CaseTags");

                    b.Navigation("CaseViewLogs");

                    b.Navigation("MedicalImages");

                    b.Navigation("QuizQuestions");

                    b.Navigation("StudentQuestions");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.MedicalImage", b =>
                {
                    b.Navigation("CaseAnnotations");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Quiz", b =>
                {
                    b.Navigation("ClassQuizzes");

                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.QuizAttempt", b =>
                {
                    b.Navigation("StudentQuizAnswers");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.QuizQuestion", b =>
                {
                    b.Navigation("StudentQuizAnswers");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.StudentQuestion", b =>
                {
                    b.Navigation("CaseAnswers");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.Tag", b =>
                {
                    b.Navigation("CaseTags");

                    b.Navigation("ClassTags");

                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("BoneVisQA.Repositories.Models.User", b =>
                {
                    b.Navigation("AcademicClasses");

                    b.Navigation("CaseAnswers");

                    b.Navigation("CaseViewLogs");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("ExpertReviews");

                    b.Navigation("LearningStatistics");

                    b.Navigation("QuizAttempts");

                    b.Navigation("StudentQuestions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
